apiVersion: v1
kind: Secret
metadata:
  labels:
    app: scalera-traffic-exporter
  name: scalera-api-secret
  namespace: monitoring
type: Opaque
data:
  SCALERA_API_KEY: YOUR_BASE64_API_KEY
  SCALERA_API_PASSWORD: YOUR_BASE64_API_PASSWORD
  SCALERA_URL: SCALERA_URL_BASE64_FORMAT
