apiVersion: v1
kind: Service
metadata:
  labels:
    app: softaculous-traffic-exporter
  name: softaculous-traffic-exporter-svc
  namespace: monitoring
spec:
  type: ClusterIP
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    app: softaculous-traffic-exporter
