apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: softaculous-traffic-exporter
    release: kwc-monitoring
  name: softaculous-traffic-exporter
  namespace: monitoring
spec:
  endpoints:
  - path: /metrics
    port: metrics
    scheme: http
  jobLabel: ajor-softaculous
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: softaculous-traffic-exporter
